### ISSUE TITLE
[Feature-Request] Placing/Breaking World Blacklist 

### ISSUE THREAD

**Issue by Tomi010817** [timbru31/SilkSpawners#306]
# Feature Request

## Feature Description
 A placing and breaking world blacklist options so you can disable these actions on certain worlds of specific spawner mobtypes. This option would not break any user data, and it would be pretty useful for deciding which world you want to disable the placing or breaking of specific spawners mobtypes. There are two examples at the end of this post explaining how these two options would look.

## Motivation Behind Feature
 The motivation behind this feature, is mainly because I wanted to disable the placing of skeleton spawners on the nether world.
But I've been thinking about it, and I concluded that this feature would be very useful for a lot of people who uses this plugin, since it would allow us to decide if we want to disable or not, the placing and breaking of specific spawners mobtypes on certain worlds.

## /version output?
![2021-02-24_02 22 28](https://user-images.githubusercontent.com/43190931/108952235-ea43ce80-7647-11eb-9e39-ea791d64bce8.png)

## SilkSpawners version
SilkSpawners v7.0.0

## Please provide any additional information below.
How would these new options look?

---
**Example 1:**
```
  Skeleton:
    enable: true
    enableCraftingSpawner: true
    enableSpawnEggOverride: true
    displayName: Esqueletos
    placingWorldBlacklist: []
    breakingWorldBlacklist: []
```
 On this example, you can see that these two new options are called "placingWorldBlacklist" and "breakingWorldBlacklist", and the input "[]" means that there aren't any worlds on those blacklists, so the Skeleton spawner will be able to be placed on any world. This would be the default value for those two options on every spawner, so, that way, it won't conflict with players current setups when implementing this feature.

---
**Example 2:**
```
  Skeleton:
    enable: true
    enableCraftingSpawner: true
    enableSpawnEggOverride: true
    displayName: Esqueletos
    placingWorldBlacklist:
      - ExampleWorld123
      - world_nether
    breakingWorldBlacklist:
      - ExampleWorld123
```
 So this time, the players won't be able to neither place or break Skeleton spawners when inside the world "ExampleWorld123", and they won't be able to place  Skeleton spawners inside the world "world_nether" yet they will be able to break them in case some spawner is found placed.

---
_PD: A permission to be able to break and place on blacklisted worlds (for staff) would be very sweet._
