### ISSUE TITLE
Silkspawners Drop Rate

### ISSUE THREAD

**Issue by TheFrikandel** [timbru31/SilkSpawners#95]
## What steps will reproduce the problem?
I gave my players from a certain rank the ability to mine spawners and the will drop always. But it gives them the same drop rate as my default rank. (50%)

## My Plugins
http://prntscr.com/gdlsf6
http://prntscr.com/gdlsi8

## Silkspawners CONFIG
```yaml
# See documentation at https://dev.bukkit.org/projects/silkspawners/pages/configuration
 
# Should the plugin automatically update if an update is available?
autoUpdater: true
 
# Should a permission be required when a spawner explodes by TNT to achieve a drop
permissionExplode: false
 
# Should be checked for WorldGuard build ability to change spawners
useWorldGuard: true
 
# Percentage of dropping a spawner block when TNT or creepers explode
explosionDropChance: 30
 
# Percentage of dropping a iron bars when a spawner is mined
destroyDropChance: 100
 
# Percentage of dropping an egg when a spawner is mined
eggDropChance: 100
 
# Percentage of dropping the spawner when mined
silkDropChance: 50
 
# When generic spawner items are placed, spawn this creature (e.g. from /give or other plugins)
# PIG (90) is Minecraft default (put NAMES or IDs here!)
defaultCreature: 90
 
# How far is the spawner reachable with your crosshair (disable with -1)
spawnerCommandReachDistance: 6
 
# Minimum silk touch level [can be changed via other plugins to a higher value]
# Set it to 0 to mine it without silk touch
minSilkTouchLevel: 1
 
# If a player in creative destroys a spawner nothing is dropped
noDropsCreative: true
 
# If a spawner is destroyed, should the egg be dropped
destroyDropEgg: false
 
# If a spawner is destroyed, should XP be dropped
destroyDropXP: 0
 
# If a spawner is mined, should it be directly added to the inventory of the player
dropSpawnerToInventory: false
 
# Amount of spawners to be dropped when mined with valid silk touch
dropAmount: 1
 
# Flag a spawner as already mined to prevent XP duping
preventXPFarming: false
 
# Drops XP only when a spawner is destroyed and not mined via silk touch
dropXPOnlyOnDestroy: false
 
# If a spawner is destroyed, should iron bars be dropped
destroyDropBars: 0
 
# Should the player be able to craft spawners
craftableSpawners: false
 
# Leave a slot empty (null/air)? Just make a space then, example 'A A' -> middle is free
# X is always the egg
recipeTop: AAA
recipeMiddle: AXA
recipeBottom: AAA
recipeAmount: 1
 
# Custom example:
#recipeTop: 'A A'
#recipeMiddle: 'BXA'
#recipeBottom: 'C D'
#ingredients:
#  - 'A,IRON_FENCE'
#  - 'B,DIRT'
#  - 'C,2'
#  - 'D,5'
 
# You can put IDs or the NAME here (please uppercase)
# Add it for each custom ingredient you add, too!
ingredients:
- A,IRON_FENCE
 
# Should spawners be unstackable
spawnersUnstackable: false
 
# Should the egg be consumed when the spawner is changed with it
consumeEgg: true
 
# Fallback if the creature should be enabled, if not specified for the entity
enableCreatureDefault: true
 
# Should numbers be ignored (on eggs) and allow every number value?
ignoreCheckNumbers: false
 
# Disable left click to change spawners, spawns a mob instead. Still blocks Vanilla right click behavior.
disableChangeTypeWithEgg: false
 
# Should instead of spawning a mob a MonsterSpawner be placed? (Uses consumeEgg value, too)
spawnEggToSpawner: false
 
# Should the spawn algorithm be overridden? Allows spawning of non-standard entities
spawnEggOverride: false
 
# Fallback if the creature should be spawned, if not specified for the entity
spawnEggOverrideSpawnDefault: true
 
# Allowed set of tools which can mine a spawner. IDs are supported, too
allowedTools:
- WOOD_PICKAXE
- STONE_PICKAXE
- IRON_PICKAXE
- GOLD_PICKAXE
- DIAMOND_PICKAXE
 
# Amount of spawners or eggs given to a player when the argument is omitted
defaultAmountGive: 1
 
# Notify the player about the spawner when he clicks it in the inventory
notifyOnClick: true
 
# Notify the player about the spawner when he holds the spawner in the hand
notifyOnHold: true
 
# Configure displaying with BarAPI, time is in seconds
barAPI:
  enable: false
  displayTime: 3
 
# Configure displaying with 1.9 BossBarApi, time is in seconds
vanillaBossBar:
  enable: false
  displayTime: 3
 
  # Valid colors are BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  color: RED
 
  # Valid styles are SEGMENTED_10, SEGMENTED_12, SEGMENTED_20, SEGMENTED_6, SOLID
  style: SOLID
 
# Prevent that a spawner is changed via eggs in other territories
factionsSupport: false
 
# Prevent that a spawner is changed via eggs in other kingdoms
feudalSupport: false
 
# Puts more information out on startup
verboseConfig: false
 
# Internal stuff, do NOT change unless advised - the plugin might break otherwise
useReflection: true
testMCVersion: true
useMetadata: true
useLegacyName: false
```
## What ive tried

    - silkspawners.drop.*
    - silkspawners.place.*
    - silkspawners.silkdrop.*
    - silkspawners.destroydrop.*

None of those worked ^^

## Version

27.08 15:07:36 [Server] INFO Authors: xGhOsTkiLLeRx and mushroomhostage
27.08 15:07:36 [Server] INFO pick up and move monster spawners using silk touch
27.08 15:07:36 [Server] INFO SilkSpawners version 5.0.0

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)
